In [5]:
from sklearn.datasets import fetch_california_housing

In [13]:
df = fetch_california_housing(as_frame=True)

In [14]:
df

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude
 0        -122.23
 1        -122.22
 2        -122.24
 3        -122.25
 4        -122.25
 ...          ...
 20635    -121.09
 20636    -121.21
 20637    -121.22
 20638    -121.32
 20639    -121.24

 [20640 rows x 8 columns],
 'target': 0        4.526
 1        3.585
 2        3.521
 3        3.413
 4        3.422
          ...
 20635    0.781
 20636    0.771
 20637    0.923
 20638    0.847
 20639    0.894
 Name: MedHouseVal, Length: 20640, dtype: float64,
 'frame':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude  MedHouseVal
 0        -122.23        4.526
 1        -122.22        3.585
 2        -122.24        3.521
 3        -122.25        3.413
 4        -122.25        3.422
 ...          ...          ...
 20635    -121.09        0.781
 20636    -121.21        0.771
 20637    -121.22        0.923
 20638    -121.32        0.847
 20639    -121.24        0.894

 [20640 rows x 9 columns],
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [15]:
x = df.data.head(2000).copy()

In [16]:
y = df.target.head(2000).copy()

In [17]:
import numpy as np

In [19]:
np.random.seed(42)

In [20]:
x['Noise_Uniform'] = np.random.rand(len(x))
x['Noise_Normal'] = np.random.randn(len(x))
x['Noise_Integers'] = np.random.randint(0, 100, len(x))

In [21]:
from sklearn.feature_selection import mutual_info_regression as MIR

In [23]:
mir_score = pd.Series(MIR(x,y,random_state=42), index=x.columns).sort_values(ascending=False)

In [24]:
print(f'Mutual info score:\n {mir_score}')

Mutual info score:
 MedInc            0.569456
Latitude          0.540790
Longitude         0.440040
AveRooms          0.213597
AveBedrms         0.094108
HouseAge          0.058092
AveOccup          0.021436
Population        0.008584
Noise_Uniform     0.003577
Noise_Normal      0.000000
Noise_Integers    0.000000
dtype: float64

In [25]:
keep = mir_score[mir_score>0.01].index.tolist()

In [26]:
print(f'Values kept after MIR score:\n{keep}')

Values kept after MIR score:
['MedInc', 'Latitude', 'Longitude', 'AveRooms', 'AveBedrms', 'HouseAge', 'AveOccup']

In [28]:
from sklearn.preprocessing import StandardScaler as SS

In [29]:
x_scaled = SS().fit_transform(x[keep])

In [30]:
from sklearn.decomposition import PCA

In [31]:
pca=PCA(n_components=2)

In [32]:
x_pca=pca.fit_transform(x_scaled)

In [33]:
df_pca=pd.DataFrame(x_pca, columns=['PC1','PC2'])

In [34]:
df_pca

           PC1       PC2
0    -0.284443 -1.783026
1    -0.039083 -1.318181
2    -0.333148 -1.811070
3    -0.659095 -1.134829
4    -0.620355 -0.525320
...        ...       ...
1995  0.472044  0.105971
1996  0.516319 -0.261949
1997  0.506961  0.132478
1998  0.557254  0.069883
1999  0.980332  0.899388

[2000 rows x 2 columns]

In [35]:
var1,var2=pca.explained_variance_ratio_

In [36]:
print(f"PC1: {var1*100:.2f}% | PC2: {var2*100:.2f}% | Total: {(var1+var2)*100:.2f}%")

PC1: 31.33% | PC2: 19.16% | Total: 50.49%

In [37]:
#using 90% method

In [38]:
pca=PCA(n_components=0.90)

In [39]:
X_pca = pca.fit_transform(x_scaled)

num_components_kept = X_pca.shape[1]
print(f"--> PCA dynamically retained {num_components_kept} components to hit the 90% threshold.")

component_names = [f'PC{i+1}' for i in range(num_components_kept)]

df_pca = pd.DataFrame(data=X_pca, columns=component_names)

--> PCA dynamically retained 5 components to hit the 90% threshold.

In [40]:
df_pca

           PC1       PC2       PC3       PC4       PC5
0    -0.284443 -1.783026 -0.508477 -0.842253 -0.615051
1    -0.039083 -1.318181 -1.341436 -1.667866 -0.607122
2    -0.333148 -1.811070  0.280083 -0.219293 -0.492272
3    -0.659095 -1.134829  0.733906 -0.274816 -0.235226
4    -0.620355 -0.525320  1.378083 -0.436480 -0.001531
...        ...       ...       ...       ...       ...
1995  0.472044  0.105971 -0.263564  2.502940  4.219700
1996  0.516319 -0.261949  0.015694  3.623583  4.126348
1997  0.506961  0.132478 -0.005080  1.758117  4.258574
1998  0.557254  0.069883 -0.614460  2.888864  4.111385
1999  0.980332  0.899388 -0.708790  0.095811  4.294146

[2000 rows x 5 columns]